import os
import sys
import requests

def print_welcome_message(fname, lname):
    print(f"Welcome to Jenkins Demo Script, {fname} {lname}!")

def perform_math_operations():
    print("Performing some math operations:")
    a = 5
    b = 3.2
    print(f"{a} + {b} = {a + b}")
    print(f"{a} - {b} = {a - b}")
    print(f"{a} * {b} = {a * b}")
    print(f"{a} / {b} = {a / b}")

def fetch_api_data():
    print("Fetching data from an external API (https://jsonplaceholder.typicode.com/todos/1):")
    response = requests.get("https://jsonplaceholder.typicode.com/todos/1")
    if response.status_code == 200:
        data = response.json()
        print("Data fetched successfully!")
        print(data)
    else:
        print("Failed to fetch data from the API.")

def write_output_to_file():
    print("Writing output to file 'output.txt'")
    with open("output.txt", "w") as file:
        file.write("This is an output file generated by the Jenkins demo script.\n")
        file.write("Feel free to explore Jenkins' capabilities!\n")

def print_environment_variables():
    print("Printing environment variables:")
    for key, value in os.environ.items():
        print(f"{key}: {value}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 ex51.py <first_name> <last_name>")
        sys.exit(1)
    fname = sys.argv[1]
    lname = sys.argv[2]

    print_welcome_message(fname, lname)
    perform_math_operations()
    fetch_api_data()
    write_output_to_file()
    print_environment_variables()
